# Generated by Django 2.0.5 on 2018-05-16 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubcate',
            name='subcat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cat.SubCategory'),
        ),
    ]
